# Generated by Django 2.1.5 on 2019-04-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190323_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='text_body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
        migrations.AddField(
            model_name='ad',
            name='short_description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='message',
            name='body_text',
            field=models.TextField(default='', max_length=1255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.TextField(max_length=125),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='accounts.Chat'),
        ),
    ]
