# Generated by Django 2.2.1 on 2019-05-23 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190517_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default=datetime.date(2019, 5, 23)),
        ),
    ]
