# Generated by Django 2.2.1 on 2019-06-19 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20190618_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
    ]
