# Generated by Django 2.2.1 on 2019-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20190619_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Is super user', verbose_name='is_superuser'),
        ),
    ]
