# Generated by Django 2.2.1 on 2019-05-24 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20190523_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default=datetime.date(2019, 5, 24)),
        ),
    ]
