REGISTER_USER = 'http://localhost:8080/system/users/register/'
CREATE_AD = 'http://localhost:8080/system/ads/' 
GET_AD_BY_ID = 'http://localhost:8080/system/ads/'
GET_ADS = 'http://localhost:8080/system/ads-page?'
GET_ADS_BY_USER_EMAIL = 'http://localhost:8080/system/ads-user?email='