# Generated by Django 2.2.1 on 2019-06-24 12:31

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Fetaured')),
                ('title', models.CharField(default=None, max_length=255)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('HEADSETS', 'HEADSETS'), ('KEYS', 'KEYS')], default=None, max_length=64)),
                ('short_description', models.CharField(default=None, max_length=120)),
                ('personality', models.CharField(choices=[('COMPANY', 'COMPANY'), ('PRIVATE_PERSON', 'PRIVATE_PERSON')], default=None, max_length=64)),
                ('description', models.TextField(default=None, max_length=1024)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to=core.models.location_file)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
