# Generated by Django 2.2.1 on 2019-06-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190619_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='staff account'),
        ),
    ]
